package types

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEvent_CorrelationID_AutoGenerated(t *testing.T) {
	// Given: creating a new event
	event := NewEvent(EventAgentStarted, "test-agent", "workspace-123")

	// Then: CorrelationID should be auto-generated as a valid UUID
	require.NotEmpty(t, event.CorrelationID)
	_, err := uuid.Parse(event.CorrelationID)
	assert.NoError(t, err, "CorrelationID should be a valid UUID")
}

func TestEvent_WithCorrelationID(t *testing.T) {
	// Given: a custom correlation ID
	customCorrelationID := "custom-correlation-123"

	// When: creating an event with WithCorrelationID
	event := NewEvent(EventAgentStarted, "test-agent", "workspace-123").
		WithCorrelationID(customCorrelationID)

	// Then: event should have the custom correlation ID
	assert.Equal(t, customCorrelationID, event.CorrelationID)
}

func TestEvent_CorrelationID_PropagatesAcrossEvents(t *testing.T) {
	// Given: a parent event with a correlation ID
	parentEvent := NewEvent(EventTriggerAgent, "parent-agent", "workspace-123")
	require.NotEmpty(t, parentEvent.CorrelationID)

	// When: creating a child event with the same correlation ID
	childEvent := NewEvent(EventAgentStarted, "child-agent", "workspace-123").
		WithCorrelationID(parentEvent.CorrelationID)

	// Then: both events should have the same correlation ID
	assert.Equal(t, parentEvent.CorrelationID, childEvent.CorrelationID)
}

func TestEvent_CorrelationID_UniquePerEvent(t *testing.T) {
	// Given: creating multiple events
	event1 := NewEvent(EventAgentStarted, "agent-1", "workspace-123")
	event2 := NewEvent(EventAgentStarted, "agent-2", "workspace-123")

	// Then: each event should have a unique correlation ID
	assert.NotEqual(t, event1.CorrelationID, event2.CorrelationID)
}

func TestEvent_WithCorrelationID_ChainedBuilders(t *testing.T) {
	// Given: a correlation ID and other event attributes
	correlationID := "correlation-abc-123"
	payload := map[string]interface{}{"key": "value"}

	// When: using chained builders
	event := NewEvent(EventLeadReceived, "sales-agent", "workspace-123").
		WithCorrelationID(correlationID).
		WithTargetAgent("sdr-agent").
		WithPayload(payload).
		WithPriority(PriorityHigh)

	// Then: all attributes should be set correctly
	assert.Equal(t, correlationID, event.CorrelationID)
	assert.Equal(t, "sdr-agent", event.TargetAgent)
	assert.Equal(t, payload, event.Payload)
	assert.Equal(t, PriorityHigh, event.Priority)
}
